<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises =
            [
                ["ddi" => "93", "pais" => "Afeganistão", "continente" =>"Ásia"],
                ["ddi" => "27", "pais" => "África do Sul", "continente" =>"África"],
                ["ddi" => "355", "pais" => "Albânia", "continente" =>"Europa"],
                ["ddi" => "49", "pais" => "Alemanha", "continente" =>"Europa"],
                ["ddi" => "376", "pais" => "Andorra", "continente" =>"Europa"],
                ["ddi" => "244", "pais" => "Angola", "continente" =>"África"],
                ["ddi" => "1", "pais" => "Anguilla", "continente" =>"América Central"],
                ["ddi" => "1", "pais" => "Antígua e Barbuda", "continente" =>"América Central"],
                ["ddi" => "599", "pais" => "Antilhas Holandesas", "continente" =>"América Central"],
                ["ddi" => "966", "pais" => "Arábia Saudita", "continente" =>"Ásia"],
                ["ddi" => "213", "pais" => "Argélia", "continente" =>"África"],
                ["ddi" => "54", "pais" => "Argentina", "continente" =>"América do Sul"],
                ["ddi" => "374", "pais" => "Armênia", "continente" =>"Ásia"],
                ["ddi" => "297", "pais" => "Aruba", "continente" =>"América Central"],
                ["ddi" => "247", "pais" => "Ascensão", "continente" =>"África"],
                ["ddi" => "61", "pais" => "Austrália", "continente" =>"Oceania"],
                ["ddi" => "43", "pais" => "Áustria", "continente" =>"Europa"],
                ["ddi" => "994", "pais" => "Azerbaijão", "continente" =>"Ásia"],
                ["ddi" => "1", "pais" => "Bahamas", "continente" =>"América Central"],
                ["ddi" => "880", "pais" => "Bangladesh", "continente" =>"Ásia"],
                ["ddi" => "1", "pais" => "Barbados", "continente" =>"América Central"],
                ["ddi" => "973", "pais" => "Bahrein", "continente" =>"Ásia"],
                ["ddi" => "32", "pais" => "Bélgica", "continente" =>"Europa"],
                ["ddi" => "501", "pais" => "Belize", "continente" =>"América Central"],
                ["ddi" => "229", "pais" => "Benim", "continente" =>"África"],
                ["ddi" => "1", "pais" => "Bermudas", "continente" =>"América Central"],
                ["ddi" => "375", "pais" => "Bielorrússia", "continente" =>"Europa"],
                ["ddi" => "591", "pais" => "Bolívia", "continente" =>"América do Sul"],
                ["ddi" => "387", "pais" => "Bósnia e Herzegovina", "continente" =>"Europa"],
                ["ddi" => "267", "pais" => "Botswana", "continente" =>"África"],
                ["ddi" => "55", "pais" => "Brasil", "continente" =>"América do Sul"],
                ["ddi" => "673", "pais" => "Brunei", "continente" =>"Ásia"],
                ["ddi" => "359", "pais" => "Bulgária", "continente" =>"Europa"],
                ["ddi" => "226", "pais" => "Burkina Faso", "continente" =>"África"],
                ["ddi" => "257", "pais" => "Burundi", "continente" =>"África"],
                ["ddi" => "975", "pais" => "Butão", "continente" =>"Ásia"],
                ["ddi" => "238", "pais" => "Cabo Verde", "continente" =>"África"],
                ["ddi" => "237", "pais" => "Camarões", "continente" =>"África"],
                ["ddi" => "855", "pais" => "Camboja", "continente" =>"Ásia"],
                ["ddi" => "1", "pais" => "Canadá", "continente" =>"América do Norte"],
                ["ddi" => "7", "pais" => "Cazaquistão", "continente" =>"Ásia"],
                ["ddi" => "237", "pais" => "Chade", "continente" =>"África"],
                ["ddi" => "56", "pais" => "Chile", "continente" =>"América do Sul"],
                ["ddi" => "86", "pais" => "República Popular da China", "continente" =>"Ásia"],
                ["ddi" => "357", "pais" => "Chipre", "continente" =>"Europa"],
                ["ddi" => "57", "pais" => "Colômbia", "continente" =>"América do Sul"],
                ["ddi" => "269", "pais" => "Comores", "continente" =>"África"],
                ["ddi" => "242", "pais" => "Congo-Brazzaville", "continente" =>"África"],
                ["ddi" => "243", "pais" => "Congo-Kinshasa", "continente" =>"África"],
                ["ddi" => "850", "pais" => "Coreia do Norte", "continente" =>"Ásia"],
                ["ddi" => "82", "pais" => "Coreia do Sul", "continente" =>"Ásia"],
                ["ddi" => "225", "pais" => "Costa do Marfim", "continente" =>"África"],
                ["ddi" => "506", "pais" => "Costa Rica", "continente" =>"América Central"],
                ["ddi" => "385", "pais" => "Croácia", "continente" =>"Europa"],
                ["ddi" => "53", "pais" => "Cuba", "continente" =>"América Central"],
                ["ddi" => "45", "pais" => "Dinamarca", "continente" =>"Europa"],
                ["ddi" => "253", "pais" => "Djibuti", "continente" =>"África"],
                ["ddi" => "1", "pais" => "Dominica", "continente" =>"América Central"],
                ["ddi" => "20", "pais" => "Egipto", "continente" =>"África/Ásia"],
                ["ddi" => "503", "pais" => "El Salvador", "continente" =>"América Central"],
                ["ddi" => "971", "pais" => "Emirados Árabes Unidos", "continente" =>"Ásia"],
                ["ddi" => "593", "pais" => "Equador", "continente" =>"América do Sul"],
                ["ddi" => "291", "pais" => "Eritreia", "continente" =>"África"],
                ["ddi" => "421", "pais" => "Eslováquia", "continente" =>"Europa"],
                ["ddi" => "386", "pais" => "Eslovénia", "continente" =>"Europa"],
                ["ddi" => "34", "pais" => "Espanha", "continente" =>"Europa"],
                ["ddi" => "1", "pais" => "Estados Unidos", "continente" =>"América do Norte"],
                ["ddi" => "372", "pais" => "Estónia", "continente" =>"Europa"],
                ["ddi" => "251", "pais" => "Etiópia", "continente" =>"África"],
                ["ddi" => "679", "pais" => "Fiji", "continente" =>"Oceania"],
                ["ddi" => "63", "pais" => "Filipinas", "continente" =>"Ásia"],
                ["ddi" => "358", "pais" => "Finlândia", "continente" =>"Europa"],
                ["ddi" => "33", "pais" => "França", "continente" =>"Europa"],
                ["ddi" => "241", "pais" => "Gabão", "continente" =>"África"],
                ["ddi" => "220", "pais" => "Gâmbia", "continente" =>"África"],
                ["ddi" => "233", "pais" => "Gana", "continente" =>"África"],
                ["ddi" => "995", "pais" => "Geórgia", "continente" =>"Ásia"],
                ["ddi" => "350", "pais" => "Gibraltar", "continente" =>"Europa"],
                ["ddi" => "1", "pais" => "Granada", "continente" =>"América Central"],
                ["ddi" => "30", "pais" => "Grécia", "continente" =>"Europa"],
                ["ddi" => "299", "pais" => "Groenlândia", "continente" =>"América do Norte"],
                ["ddi" => "590", "pais" => "Guadalupe", "continente" =>"América Central"],
                ["ddi" => "671", "pais" => "Guam", "continente" =>"Oceania"],
                ["ddi" => "502", "pais" => "Guatemala", "continente" =>"América Central"],
                ["ddi" => "592", "pais" => "Guiana", "continente" =>"América do Sul"],
                ["ddi" => "594", "pais" => "Guiana Francesa", "continente" =>"América do Sul"],
                ["ddi" => "224", "pais" => "Guiné", "continente" =>"África"],
                ["ddi" => "245", "pais" => "Guiné-Bissau", "continente" =>"África"],
                ["ddi" => "240", "pais" => "Guiné Equatorial", "continente" =>"África"],
                ["ddi" => "509", "pais" => "Haiti", "continente" =>"América Central"],
                ["ddi" => "504", "pais" => "Honduras", "continente" =>"América Central"],
                ["ddi" => "852", "pais" => "Hong Kong", "continente" =>"Ásia"],
                ["ddi" => "36", "pais" => "Hungria", "continente" =>"Europa"],
                ["ddi" => "967", "pais" => "Iêmen", "continente" =>"Ásia"],
                ["ddi" => "1", "pais" => "Ilhas Cayman", "continente" =>"América Central"],
                ["ddi" => "672", "pais" => "Ilha Christmas", "continente" =>"Oceania"],
                ["ddi" => "672", "pais" => "Ilhas Cocos", "continente" =>"Oceania"],
                ["ddi" => "682", "pais" => "Ilhas Cook", "continente" =>"Oceania"],
                ["ddi" => "298", "pais" => "Ilhas Féroe", "continente" =>"Europa"],
                ["ddi" => "672", "pais" => "Ilha Heard e Ilhas McDonald", "continente" =>"Oceania"],
                ["ddi" => "960", "pais" => "Maldivas", "continente" =>"Ásia"],
                ["ddi" => "500", "pais" => "Ilhas Malvinas", "continente" =>"América do Sul"],
                ["ddi" => "1", "pais" => "Ilhas Marianas do Norte", "continente" =>"Oceania"],
                ["ddi" => "692", "pais" => "Ilhas Marshall", "continente" =>"Oceania"],
                ["ddi" => "672", "pais" => "Ilha Norfolk", "continente" =>"Oceania"],
                ["ddi" => "677", "pais" => "Ilhas Salomão", "continente" =>"Oceania"],
                ["ddi" => "1", "pais" => "Ilhas Virgens Americanas", "continente" =>"América Central"],
                ["ddi" => "1", "pais" => "Ilhas Virgens Britânicas", "continente" =>"América Central"],
                ["ddi" => "91", "pais" => "Índia", "continente" =>"Ásia"],
                ["ddi" => "62", "pais" => "Indonésia", "continente" =>"Ásia/Oceania"],
                ["ddi" => "98", "pais" => "Irã", "continente" =>"Ásia"],
                ["ddi" => "964", "pais" => "Iraque", "continente" =>"Ásia"],
                ["ddi" => "353", "pais" => "Irlanda", "continente" =>"Europa"],
                ["ddi" => "354", "pais" => "Islândia", "continente" =>"Europa"],
                ["ddi" => "972", "pais" => " Israel", "continente" =>"Ásia"],
                ["ddi" => "39", "pais" => "Itália", "continente" =>"Europa"],
                ["ddi" => "1", "pais" => "Jamaica", "continente" =>"América Central"],
                ["ddi" => "81", "pais" => "Japão", "continente" =>"Ásia"],
                ["ddi" => "962", "pais" => "Jordânia", "continente" =>"Ásia"],
                ["ddi" => "686", "pais" => "Kiribati", "continente" =>"Oceania"],
                ["ddi" => "383", "pais" => "Kosovo", "continente" =>"Europa"],
                ["ddi" => "965", "pais" => "Kuwait", "continente" =>"Ásia"],
                ["ddi" => "856", "pais" => "Laos", "continente" =>"Ásia"],
                ["ddi" => "266", "pais" => "Lesoto", "continente" =>"África"],
                ["ddi" => "371", "pais" => "Letônia", "continente" =>"Europa"],
                ["ddi" => "961", "pais" => "Líbano", "continente" =>"Ásia"],
                ["ddi" => "231", "pais" => "Libéria", "continente" =>"África"],
                ["ddi" => "218", "pais" => "Líbia", "continente" =>"África"],
                ["ddi" => "423", "pais" => "Liechtenstein", "continente" =>"Europa"],
                ["ddi" => "370", "pais" => "Lituânia", "continente" =>"Europa"],
                ["ddi" => "352", "pais" => "Luxemburgo", "continente" =>"Europa"],
                ["ddi" => "853", "pais" => "Macau", "continente" =>"Ásia"],
                ["ddi" => "389", "pais" => "República da Macedônia", "continente" =>"Europa"],
                ["ddi" => "261", "pais" => "Madagascar", "continente" =>"África"],
                ["ddi" => "60", "pais" => "Malásia", "continente" =>"Ásia"],
                ["ddi" => "265", "pais" => "Malawi", "continente" =>"África"],
                ["ddi" => "223", "pais" => "Mali", "continente" =>"África"],
                ["ddi" => "356", "pais" => "Malta", "continente" =>"Europa"],
                ["ddi" => "212", "pais" => "Marrocos", "continente" =>"África"],
                ["ddi" => "596", "pais" => "Martinica", "continente" =>"América Central"],
                ["ddi" => "230", "pais" => "Maurícia", "continente" =>"África"],
                ["ddi" => "222", "pais" => "Mauritânia", "continente" =>"África"],
                ["ddi" => "269", "pais" => "Mayotte", "continente" =>"África"],
                ["ddi" => "52", "pais" => "México", "continente" =>"América do Norte"],
                ["ddi" => "691", "pais" => "Estados Federados da Micronésia", "continente" =>"Oceania"],
                ["ddi" => "258", "pais" => "Moçambique", "continente" =>"África"],
                ["ddi" => "373", "pais" => "Moldávia", "continente" =>"Europa"],
                ["ddi" => "377", "pais" => "Mônaco", "continente" =>"Europa"],
                ["ddi" => "976", "pais" => "Mongólia", "continente" =>"Ásia"],
                ["ddi" => "382", "pais" => "Montenegro", "continente" =>"Europa"],
                ["ddi" => "1", "pais" => "Montserrat", "continente" =>"América Central"],
                ["ddi" => "95", "pais" => "Myanmar", "continente" =>"Ásia"],
                ["ddi" => "264", "pais" => "Namíbia", "continente" =>"África"],
                ["ddi" => "674", "pais" => "Nauru", "continente" =>"Oceania"],
                ["ddi" => "977", "pais" => "Nepal", "continente" =>"Ásia"],
                ["ddi" => "505", "pais" => "Nicarágua", "continente" =>"América Central"],
                ["ddi" => "227", "pais" => "Níger", "continente" =>"África"],
                ["ddi" => "234", "pais" => "Nigéria", "continente" =>"África"],
                ["ddi" => "683", "pais" => "Niue", "continente" =>"Oceania"],
                ["ddi" => "47", "pais" => "Noruega", "continente" =>"Europa"],
                ["ddi" => "687", "pais" => "Nova Caledônia", "continente" =>"Oceania"],
                ["ddi" => "64", "pais" => "Nova Zelândia", "continente" =>"Oceania"],
                ["ddi" => "968", "pais" => "Omã", "continente" =>"Ásia"],
                ["ddi" => "31", "pais" => "Países Baixos", "continente" =>"Europa"],
                ["ddi" => "680", "pais" => "Palau", "continente" =>"Oceania"],
                ["ddi" => "970", "pais" => "Palestina", "continente" =>"Ásia"],
                ["ddi" => "507", "pais" => "Panamá", "continente" =>"América Central"],
                ["ddi" => "675", "pais" => "Papua-Nova Guiné", "continente" =>"Oceania"],
                ["ddi" => "92", "pais" => "Paquistão", "continente" =>"Ásia"],
                ["ddi" => "595", "pais" => "Paraguai", "continente" =>"América do Sul"],
                ["ddi" => "51", "pais" => "Peru", "continente" =>"América do Sul"],
                ["ddi" => "689", "pais" => "Polinésia Francesa", "continente" =>"Oceania"],
                ["ddi" => "48", "pais" => "Polônia", "continente" =>"Europa"],
                ["ddi" => "1", "pais" => "Porto Rico", "continente" =>"América Central"],
                ["ddi" => "351", "pais" => "Portugal", "continente" =>"Europa"],
                ["ddi" => "974", "pais" => "Qatar", "continente" =>"Ásia"],
                ["ddi" => "254", "pais" => "Quênia", "continente" =>"África"],
                ["ddi" => "996", "pais" => "Quirguistão", "continente" =>"Ásia"],
                ["ddi" => "44", "pais" => "Reino Unido", "continente" =>"Europa"],
                ["ddi" => "236", "pais" => "República Centro-Africana", "continente" =>"África"],
                ["ddi" => "1", "pais" => "República Dominicana", "continente" =>"América Central"],
                ["ddi" => "420", "pais" => "República Tcheca", "continente" =>"Europa"],
                ["ddi" => "262", "pais" => "Reunião", "continente" =>"África"],
                ["ddi" => "40", "pais" => "Romênia", "continente" =>"Europa"],
                ["ddi" => "250", "pais" => "Ruanda", "continente" =>"África"],
                ["ddi" => "7", "pais" => "Rússia", "continente" =>"Europa/Ásia"],
                ["ddi" => "212", "pais" => "Saara Ocidental", "continente" =>"África"],
                ["ddi" => "685", "pais" => "Samoa", "continente" =>"Oceania"],
                ["ddi" => "1", "pais" => "Samoa Americana", "continente" =>"Oceania"],
                ["ddi" => "290", "pais" => "Santa Helena (território)", "continente" =>"África"],
                ["ddi" => "1", "pais" => "Santa Lúcia", "continente" =>"América Central"],
                ["ddi" => "1", "pais" => "São Cristóvão e Nevis", "continente" =>"América Central"],
                ["ddi" => "378", "pais" => "São Marinho", "continente" =>"Europa"],
                ["ddi" => "508", "pais" => "Saint-Pierre e Miquelon", "continente" =>"América do Norte"],
                ["ddi" => "239", "pais" => "São Tomé e Príncipe", "continente" =>"África"],
                ["ddi" => "1", "pais" => "São Vicente e Granadinas", "continente" =>"América Central"],
                ["ddi" => "248", "pais" => "Seicheles", "continente" =>"África"],
                ["ddi" => "221", "pais" => "Senegal", "continente" =>"África"],
                ["ddi" => "232", "pais" => "Serra Leoa", "continente" =>"África"],
                ["ddi" => "381", "pais" => "Sérvia", "continente" =>"Europa"],
                ["ddi" => "65", "pais" => "Singapura", "continente" =>"Ásia"],
                ["ddi" => "963", "pais" => "Síria", "continente" =>"Ásia"],
                ["ddi" => "252", "pais" => "Somália", "continente" =>"África"],
                ["ddi" => "94", "pais" => "Sri Lanka", "continente" =>"Ásia"],
                ["ddi" => "268", "pais" => "Suazilândia", "continente" =>"África"],
                ["ddi" => "249", "pais" => "Sudão", "continente" =>"África"],
                ["ddi" => "211", "pais" => "Sudão do Sul", "continente" =>"África"],
                ["ddi" => "46", "pais" => "Suécia", "continente" =>"Europa"],
                ["ddi" => "41", "pais" => "Suíça", "continente" =>"Europa"],
                ["ddi" => "597", "pais" => "Suriname", "continente" =>"América do Sul"],
                ["ddi" => "992", "pais" => "Tadjiquistão", "continente" =>"Ásia"],
                ["ddi" => "66", "pais" => "Tailândia", "continente" =>"Ásia"],
                ["ddi" => "886", "pais" => "República da China", "continente" =>"Ásia"],
                ["ddi" => "255", "pais" => "Tanzânia", "continente" =>"África"],
                ["ddi" => "246", "pais" => "Território Britânico do Oceano Índico", "continente" =>"África"],
                ["ddi" => "670", "pais" => "Timor-Leste", "continente" =>"Ásia"],
                ["ddi" => "228", "pais" => "Togo", "continente" =>"África"],
                ["ddi" => "690", "pais" => "Tokelau", "continente" =>"Oceania"],
                ["ddi" => "676", "pais" => "Tonga", "continente" =>"Oceania"],
                ["ddi" => "1", "pais" => "Trinidad e Tobago", "continente" =>"América Central"],
                ["ddi" => "216", "pais" => "Tunísia", "continente" =>"África"],
                ["ddi" => "1", "pais" => "Turcas e Caicos", "continente" =>"América Central"],
                ["ddi" => "993", "pais" => "Turquemenistão", "continente" =>"Ásia"],
                ["ddi" => "90", "pais" => "Turquia", "continente" =>"Ásia//Europa"],
                ["ddi" => "688", "pais" => "Tuvalu", "continente" =>"Oceania"],
                ["ddi" => "380", "pais" => "Ucrânia", "continente" =>"Europa"],
                ["ddi" => "256", "pais" => "Uganda", "continente" =>"África"],
                ["ddi" => "598", "pais" => "Uruguai", "continente" =>"América do Sul"],
                ["ddi" => "998", "pais" => "Uzbequistão", "continente" =>"Ásia"],
                ["ddi" => "678", "pais" => "Vanuatu", "continente" =>"Oceania"],
                ["ddi" => "379", "pais" => "Vaticano", "continente" =>"Europa"],
                ["ddi" => "58", "pais" => "Venezuela", "continente" =>"América do Sul"],
                ["ddi" => "84", "pais" => "Vietnã", "continente" =>"Ásia"],
                ["ddi" => "681", "pais" => "Wallis e Futuna", "continente" =>"Oceania"],
                ["ddi" => "260", "pais" => "Zâmbia", "continente" =>"África"],
                ["ddi" => "263", "pais" => "Zimbábue", "continente" =>"África"]
            ];

        foreach ($paises as $pais){
            Pais::create($pais);
        }
    }
}
